### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by Kreeony** [xxcodianxx/youtube-dl-web#17]
Hi, I'm new to docker and I'm having some trouble with self-hosting. I'm using a Raspberry Pi Zero and when I try to build frontend files or start the docker container I get this message:
```
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
failed to resize tty, using default size
```
I had no problems running everything the same way in VirualBox with Ubuntu. What should I do to make it work for Raspberry Pi?

**Comment by xxcodianxx** [comment]
Hello, sorry for the late reply!

I haven't tested this software on devices like a Raspberry Pi, but here it seems that the project is incompatible with your CPU architecture (ARM version 6).

**Now, you should ask yourself as to whether you _want_ to run this on a Pi Zero.**

With 1 core and 512MB ram, I think a Pi Zero might not be able to cope with downloading two video streams, merging them with FFmpeg & uploading them out to a client - it feels like it would just be too weak. (and mind this, all of this is amplified with the more clients you have using the website).

Now, **if you _are_ insane enough to do it**, it seems like you can build the frontend files locally on the Pi if you somehow manage to install NodeJS, Yarn or NPM. You just need to somehow run the `build` command from one of those package managers, for example:

```bash
(somehow install nodejs and npm for your pi)
$ cd frontend
$ npm install
$ npm run build
```

The docker image with NodeJS & Yarn I posted won't work for you, so you need to build the frontend bare metal. After that, given that everything goes well, it _might_ run, I don't know.

Let me know how it goes!

**Comment by Racool198** [comment]
real

**Comment by Racool198** [comment]
you can silence me but you can't silence the truth

**Comment by Kreeony** [comment]
I get this error message after running npm install:
```
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap       out of memory
Aborted
```
I guess Pi Zero is not powerfull enough to run it. Anyway, thanks for your help. You're doing a great job!
