### ISSUE TITLE
Hey is there a way to install this on docker windows?

### ISSUE THREAD

**Issue by heryoff** [xxcodianxx/youtube-dl-web#19]
^

**Comment by xxcodianxx** [comment]
I have not tested deployment on Windows hosts, but theoretically I see nothing that should stop it.

Instructions on how to install Docker: https://docs.docker.com/desktop/install/windows-install/
Instructions on how to install Docker Compose: https://docs.docker.com/compose/install/

Other than that, the installation (thanks to Docker) should be the same on all platforms.

**Comment by heryoff** [comment]
Yeah at the end I figured it out. Just manually running the build command.
Just one more question? Is it normal that the file name is just the “url” of the video on not the title?

**Comment by xxcodianxx** [comment]
Yes, at the moment that's how I've structured it, since returning the title as filename would be redundant - you get it from the /meta api call.

That said, I may add a toggle to download the file with the video title as its name in the GUI.
