### ISSUE TITLE
How can I change the result format from webm to mp4 or mp3?

### ISSUE THREAD

**Issue by tobycm** [xxcodianxx/youtube-dl-web#23]
Like title, would be really helpful.
Thank you.

**Comment by tobycm** [comment]
Oh and I would like the download file to have the same name as the video too

**Comment by tobycm** [comment]
I think I can do the filename, I also pushed it into my fork, it would be a convenient to name the file as the title so feel free to merge it

**Comment by xxcodianxx** [comment]
This would require remuxing the file into a different container, which could be slow & resource demanding. It can, however, be implemented as an extra toggle that the user has maybe.

I don't have too much time on my hands right now, but when I get around to it I'll look into adding a new post-processor after the video stream is received.
