### ISSUE TITLE
Allow for wider selection of base URLs to be used

### ISSUE THREAD

**Issue by rayokamoto** [xxcodianxx/youtube-dl-web#6]
Currently, only base URLs of the form `https://www.youtube.com` and `https://youtu.be` work. The fix would be to allow base URLs such as:
```
https://youtube.com
www.youtube.com
youtube.com
youtu.be
```

This would also require changing the message that pops up:
![image](https://user-images.githubusercontent.com/22254748/151770763-04ba64aa-941c-47ac-9d8c-33535617a3a6.png)

**Comment by sphars** [comment]
Would also suggest to add `music.youtube.com` URLs as well.

**Comment by xxcodianxx** [comment]
Changes added in https://github.com/xxcodianxx/youtube-dl-web/commit/1960e11b3ae76d04c277de80c924bcefb51f148b

URLs can now completely omit the `https://` part.
YouTube Music is now supported as a valid URL (`music.youtube.com`)!

The RegEx expression for this is here:
https://github.com/xxcodianxx/youtube-dl-web/blob/1960e11b3ae76d04c277de80c924bcefb51f148b/frontend/src/logic/parseVideo.ts#L6

Thanks for the issue guys!
