### ISSUE TITLE
Permit downloading non-YouTube videos 

### ISSUE THREAD

**Issue by Mennaruuk** [xxcodianxx/youtube-dl-web#7]
Currently, only YouTube links are allowed. It’d be a nice touch to allow any link. If it’s supported by yt-dlp, it should output download links. If not, an error would pop up.

**Comment by xxcodianxx** [comment]
This is quite complicated, as not all websites would have the same properties as YouTube.
Right now, the backend is not prepared to handle links from different sites well, and adding support for other sites would require supporting all their individual quirks.

While I'd like to add support for this, it probably won't happen soon.

**Comment by Mennaruuk** [comment]
Thank you for your consideration! If it's of any help, you can check out https://yaas.natan.la/ ([GitHub](https://github.com/natanlao/yaas)). I can see it supports non-YouTube links, so that might help in making things easier.
