### ISSUE TITLE
API download route is exposed

### ISSUE THREAD

**Issue by TohoEnjoyer2000** [xxcodianxx/youtube-dl-web#8]
The design expose the /dl/[id] route which can lead to easy to perform Denial of Service attacks.

**Comment by xxcodianxx** [comment]
Yeah, the API's security in general is sort of questionable... it definitely needs more security updates.

As for the exposed endpoint, I don't really see how that's a big problem, sure, people can DoS it by requesting videos over and over again, but I don't want to follow in the footsteps of other download websites and introduce limits.

If you have any suggestions (or, more appreciated, actual code!) as for how to improve the security of the API, open a PR or let me know. :)
