### ISSUE TITLE
PR_CONNECT_RESET_ERROR on your website https://yt-dlp.us.to/

### ISSUE THREAD

**Issue by doggodanubus** [xxcodianxx/youtube-dl-web#9]
https://yt-dlp.us.to/ 

Neither work I don't get a meaningful error from Firefox, Librewolf, Aurora, links 

An error occurred during a connection to yt-dlp.us.to. PR_CONNECT_RESET_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by xxcodianxx** [comment]
Sorry, the server went down temporarily, it should be back up now. :)
